# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Create a release on NuGet

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release-nuget:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main

    - name: Get version information tag
      id: get_version
      uses: battila7/get-version-action@v2
    - name: Pack
      run: dotnet pack -c Release -p:PackageVersion=${{steps.get_version.outputs.version-without-v}} -o .output --include-symbols --include-source
    - name: Publish
      env:
        API_KEY: ${{secrets.NUGET_KEY}}
      run: |
        dotnet nuget push .output/*.nupkg --api-key $API_KEY --source https://api.nuget.org/v3/index.json
        dotnet nuget push .output/*.snupkg --api-key $API_KEY --source https://symbols.nuget.org/
